Feature frontend add missing students WIP
KTH/scanned-exams pull request #49
Opened 2021-09-23 07:32 UTC by jhsware

TODO: Use proper endpoint
TODO: Figure out what the flow should be (go to verify or stay on resolve)

2021-09-23 10:01 UTC, jhsware commented
I rebased this branch on https://github.com/KTH/scanned-exams/tree/feature-add-missing-students to roll in those changes as discussed with @exacs .

Then i rebased on https://github.com/KTH/scanned-exams/tree/v1.0 to get it up to date.

2021-09-23 10:51 UTC, jhsware commented
How to test:

1. Uncomment the line "DEV_FORCE_RANDOM_ERRORS=TRUE" in .env (check .env.in if missing)
2. Remove the assignment for this course is it exists
3. Click "Start import"
4. Remove all the students with forced errors except one from the course
5. Comment out "DEV_FORCE_RANDOM_ERRORS=TRUE" and restart backend
5. Click "Fix errors" (only the student that wasn't removed will be imported)
6. Go back to "Resolve issues" step (now all  rows will be marked with missing students)
7. Click "Fix errors" (all errors will be fixed)

2021-09-24 08:48 UTC, exacs requested changes
Found a bug in backend: some exams were flagged as "imported" even when they had errors. This is fixed in this branch.

2021-09-24 08:48 UTC, exacs commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +  const [queueStatus, setQueueStatus] = React.useState("idle");
This `queueStatus` seems a duplicate of `queueStatus` of `PrepareImport` and makes this a bit difficult to follow (two internal states that contains the same data)

I suggest to lift the state to a parent component: if the queue is "working", show the "PrepareImport" component which already contains the progress bar, etc.

2021-09-24 08:52 UTC, exacs commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +  const [queueStatus, setQueueStatus] = React.useState("idle");
Maybe my comment can be fixed in a refactor actually

2021-09-24 10:23 UTC, jhsware commented
Commit 96e70b84cc7 separates list of missing students and other errors. If there are missing students a button "Fix Missing Students" is shown. 

- Button will add missing students and then attempt to reimport all exams with errors (since others could be fixed too).
- When done you move to import page in this PR, but in PR56  you will stay on "Resolve Issues".

2021-09-24 10:25 UTC, jhsware commented
Performed rebase on v1 to get fixes from latest merged PR

2021-09-24 11:07 UTC, jhsware commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +  const [queueStatus, setQueueStatus] = React.useState("idle");
I agree, better to defer at the moment because regardless of the way forward we need to improve the routing story in the app.

2021-09-24 11:23 UTC, merged