Mongodb connection pool
KTH/scanned-exams pull request #58
Opened 2021-09-24 14:43 UTC by exacs

2021-09-24 15:57 UTC, jhsware reviewed
I have tested the cases that have triggered conflicts and it works for me on my local machine.

2021-09-24 15:57 UTC, jhsware commented on backend/app-https.js
> +  await startDatabaseConnection();
Instead of having the application being responsible for connecting we could memoize `startDatabaseConnection` and call it from `getImportQueueCollection` every time. We then expose a `closeConnection` method from the importQueue.js that is used to complete tests.

The benefit is that the db connection "just works" and if we reuse the code or refactor the application one doesn't have to remember to call `startDatabaseConnection`.

2021-09-24 16:03 UTC, jhsware requested changes
I think we should merge some changes to importQueue.spec.js that I added in #57 that are related to a previous discussion about tests being dependent on execution order.

2021-09-27 06:57 UTC, exacs commented on backend/app-https.js
> +  await startDatabaseConnection();
Sounds a nice idea!

2021-09-27 09:38 UTC, jhsware approved these changes
LGTM

2021-09-27 10:05 UTC, merged