Refactor2
KTH/scanned-exams pull request #82
Opened 2021-10-21 08:04 UTC by exacs

2021-11-01 08:59 UTC, exacs commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +  } else if (examsWithOtherErrors.length > 0) {
The idea behind this PR is to show types of error one-by-one. First, we show the "missing students" problem; once it is solved (or the teacher has chosen to not do anything), we show the other problems

2021-11-01 09:04 UTC, exacs commented on frontend/src/features/import-exams/steps/PrepareImport.js
> +export default function PrepareImport({ courseId }) {
I don't understand the question. By "is hard to understand" you mean that you are expecting some form of "callback"?

2021-11-03 09:04 UTC, exacs commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +          onClick={() => doIgnoreOtherErrors()}
For users perspective this "Ignore" button is the only way forward. Since the only solution for those problems is "Contact IT support", I think the only way forward within the app is give a button just to "go forward".

2021-11-03 09:07 UTC, exacs commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +  const { mutate: doIgnoreMissingStudents } = useMutateIgnoreImportQueueErrors(
Yes for now. If we want to add/ignore specific students that's a feature.

The basic principle is that all "missing_students" must be either added or ignored. Ignored means "the user knows that the student is missing and has explicitly chosen to NOT add it to Canvas"

2021-11-03 09:10 UTC, exacs commented on frontend/src/common/api.js
> +        client.invalidateQueries(["course", courseId, "import", "status"]);
That's a good question. In my opinion, we don't need to invalidate all `["course", courseId]`. We can assume that the "setup" doesn't change when a user add exams to the queue.

2021-11-03 09:12 UTC, exacs commented on frontend/src/common/api.js
> +        client.invalidateQueries(["course", courseId, "import"]);
Invalidating `["course", courseId]` means invalidating the "setup" query, which is very unlikely to be outdated after emptying the queue so I don't think we need to invalidate it.

2021-11-03 09:19 UTC, exacs commented on frontend/src/common/api.js
> +        client.invalidateQueries(["course", courseId, "import"]);
Invalidating `["course", courseId]` means invalidating the "setup" query, which is very unlikely to be outdated after marking errors as "ignored" so I don't think we need to invalidate it.

2021-11-03 09:36 UTC, exacs commented on frontend/src/common/api.js
> +        client.invalidateQueries(["course", courseId, "import"]);
Invalidating `["course", courseId]` means invalidating the "setup" query, which is very unlikely to be outdated after emptying the queue so I don't think we need to invalidate it.

2021-11-03 12:25 UTC, jhsware commented on frontend/src/common/api.js
> +        client.invalidateQueries(["course", courseId, "import", "status"]);
What about the import-queue list? Shouldn't that be invalidated?

2021-11-03 12:45 UTC, jhsware commented on frontend/src/features/import-exams/steps/ResolveIssues.js
> +          onClick={() => doIgnoreOtherErrors()}
I still feel that this introduces a problem with no real user benefit. From a user's point of view clicking "ignore" is a destructive operation that can't be undone. They will never see the errors again and they need to contact us to manually reset the list if this was a mistake.

A safer option is to do nothing and let the user literally ignore the errors.

I think we should explain this proposed changed behaviour to Martin to get feedback. Personally I am not convinced 😅

2021-11-05 08:12 UTC, jhsware requested changes
I think we should merge this into a 1.2 branch and deploy to stage so PO can click through. I think this is a big improvement.

2021-11-05 08:46 UTC, merged