Feature allow assignments before
KTH/scanned-exams pull request #86
Opened 2021-10-28 07:10 UTC by exacs

This PR is an alternative of https://github.com/KTH/scanned-exams/pull/87.

This PR creates the assignment _without_ any `lock_date`. Instead it creates with "on paper" type which blocks all types of submissions.

After the assignment is created the assignment will have the "on paper" type until the app tries to upload the first exam.

Still todo (not included in this PR): Move the logic to its own file and add an extensive explanation

2021-11-02 14:07 UTC, jhsware requested changes
I got the impression that this was half baked. Let me know if I misunderstood something!

2021-11-02 14:07 UTC, jhsware commented on backend/api/canvasApiClient.js
> + */
We should reset the assignment to 

submission_types: ["on_paper"],
lock_at: [original_lock]

Also, I would like to suggest locking the course during file upload to avoid keeping it open during a slow call. Obviously this has to be weighed against API-limits. Perhaps we only need to unlock during one of the API calls?

2021-11-03 12:20 UTC, exacs commented on backend/api/canvasApiClient.js
> + */
No, we cannot set `submission_types: ["on_paper"]` after uploading the first exam. That will mean that we cannot upload anything. I am also not sure if all uploaded exams will be removed if we change it to "on_paper"

2021-11-03 12:22 UTC, exacs commented on backend/api/canvasApiClient.js
> +        allowed_extensions: ["pdf"],
That's interesting. Since we do more than one API call to upload exams, it would be nice to know exactly which ones require the assignment to be unlocked.

2021-11-04 08:11 UTC, jhsware commented on backend/api/canvasApiClient.js
> + */
I though the idea was to use "on_paper" as the lock-method?

2021-11-04 08:13 UTC, jhsware commented on backend/api/canvasApiClient.js
> +        allowed_extensions: ["pdf"],
I saw that you made a change. I'll mark this as resolved but agree with "it would be nice to know exactly which ones require the assignment to be unlocked."

2021-11-04 09:29 UTC, exacs commented on backend/api/canvasApiClient.js
> + */
I've tested it now and it looks like the assignments are not removed after changing to "on_paper" so yes, we can use it to lock the assignment!

2021-11-04 13:06 UTC, exacs commented
I've decided to separate the logic about creating/locking/unlocking assignments to its own file.

Can you read it to see if it makes sense? @jhsware

2021-11-04 13:23 UTC, jhsware commented
> I've decided to separate the logic about creating/locking/unlocking assignments to its own file.

I really like this!!! It clearly explains the concept and will allow a new dev (or future us) to understand and/or optimise the behaviour.

2021-11-05 13:39 UTC, jhsware reviewed
Perhaps we could merge this onto v1.2?

2021-11-09 12:49 UTC, merged