Fix add test get ladok id
KTH/scanned-exams pull request #95
Opened 2021-11-24 13:50 UTC by jhsware

Added test after bug was found in code

https://trello.com/c/sRNzzzdM

2021-11-24 15:25 UTC, exacs requested changes
I'd like to suggest some changes but they are across files so not sure where to put them:

Concept looks good. I think is nice to use `jest.mock` to mock `canvas.getAktivitetstillfalleUIDs`. That makes sense 👍 

My suggested changes are:

- To use more "realistic" values in the mocked returns. Instead of `[1]`, use `["AKT.d7c3a0d6-db0a-11eb-9f0e-c1820d16448d"]` or similar.
- Can we write a "TODO" somewhere to merge both `_getLadokId` functions in one place?

And then there is the question about `CanvasApiError`/`EndpointError` that I've written [here](https://github.com/KTH/scanned-exams/pull/95/files#diff-c5eda715f017a3424fc82f6465678823c795e8df418b07a9e49d6828bc95e1bb)

2021-11-24 15:25 UTC, exacs commented on backend/api/endpointHandlers/setupCourse.js
> +const { CanvasApiError } = require("../error");
Are we sure these are `CanvasApiError`? According to the documentation in [`backend/api/error.js`:](https://github.com/KTH/scanned-exams/blob/59abd85204639e82c92be8ceb76a2441b1c7edba/backend/api/error.js#L76)

> CanvasApiError – all errors that can occur when accessing the external system. This should be thrown at the integration layer.

These errors does not happen because Canvas was down or because Canvas API has responded with some 4xx/5xx. Instead they are business logic (for example, we don't support certain use cases).

2021-11-25 07:31 UTC, jhsware commented on backend/api/endpointHandlers/setupCourse.js
> +const { CanvasApiError } = require("../error");
Fixed in 9784661

2021-11-25 07:44 UTC, jhsware commented
- Since the getLadokId only checks length and not validity of content I think it is reasonable to KISS the test data
- I'd actually want to rewrite the business logic to make it more self explanatory directly in the endpoint:

```
    const ladokIds = await canvas.getAktivitetstillfalleUIDs(courseId);

    // Business rules
    throwIfNotExactlyOneLadokId(ladokIds);
    
    const ladokId = ladokIds[0];
```

2021-11-25 08:19 UTC, exacs commented
> * Since the getLadokId only checks length and not validity of content I think it is reasonable to KISS the test data
> * I'd actually want to rewrite the business logic to make it more self explanatory directly in the endpoint:
> 
> ```
>     const ladokIds = await canvas.getAktivitetstillfalleUIDs(courseId);
> 
>     // Business rules
>     throwIfNotExactlyOneLadokId(ladokIds);
>     
>     const ladokId = ladokIds[0];
> ```

That sounds like a nice idea!

2021-12-01 14:44 UTC, exacs commented
LGTM. I'll merge this

2021-12-01 14:44 UTC, merged